name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
env:
    IMAGE_NAME: plex-credits-detect
jobs:
    push_to_registries:
        name: Push Docker image
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
            with:
                submodules: true
          - name: Push to Docker Hub
            uses: docker/build-push-action@v1
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                repository: cjmanca/plex-credits-detect
                tag_with_ref: true
